package nl.wilcokas.luckystackworker.model;

public enum FilterEnum {
    CLIPPING_SUPPRESSION,
    PSF,
    WIENER_DECONV,
    SHARPEN,
    SIGMA_DENOISE_1,
    SIGMA_DENOISE_2,
    BILATERAL_DENOISE,
    SAVITSKY_GOLAY,
    LOCAL_CONTRAST,
    GAMMA,
    COLOR_NORMALIZE,
    RGB_BALANCE,
    SATURATION,
    DISPERSION,
    HISTOGRAM_STRETCH,
    ROTATE;
}
