package nl.wilcokas.luckystackworker.model;

public enum OperationEnum {
	RADIUS, AMOUNT, ITERATIONS, LEVEL, DENOISEAMOUNT, DENOISERADIUS, DENOISESIGMA, DENOISEITERATIONS, RED, GREEN, BLUE,
	GAMMA, SATURATION
}
