package nl.wilcokas.luckystackworker.model;

public enum OperationEnum {
    RADIUS, AMOUNT, ITERATIONS, LEVEL, DENOISE1AMOUNT, DENOISE1RADIUS, DENOISE1ITERATIONS, DENOISE2RADIUS, DENOISE2ITERATIONS, IANSAMOUNT,
    IANSRECOVERY, RED, GREEN, BLUE, PURPLE, DENOISEALGORITHM1, DENOISEALGORITHM2,
    GAMMA, SATURATION, CONTRAST, BRIGHTNESS, BACKGROUND, SAVITZKYGOLAYSIZE, SAVITZKYGOLAYAMOUNT, SAVITZKYGOLAYITERATIONS, CLIPPINGSTRENGTH,
    CLIPPINGRANGE, DERINGRADIUS, DERINGSTRENGTH, DERINGTHRESHOLD, SHARPENMODE, LOCALCONTRASTMODE, LOCALCONTRASTFINE, LOCALCONTRASTMEDIUM,
    LOCALCONTRASTLARGE,
    DISPERSIONCORRECTION, EQUALIZELOCALHISTOGRAMSSTRENGTH
}
